export const siteConfig = {
  name: "Mohamed Tarek | Developer Portfolio",
  authorName: "Mohamed Tarek",
  username: "dragonwar101",
  description:
    "Mohamed Tarek's portfolio - A modern, responsive Next.js portfolio for developers. This open-source template can be customized to showcase your own skills, projects, and professional experience.",
  url: "https://dragonwar101.github.io",
  links: {
    twitter: "https://x.com/Mohamed87072246",
    github: "https://github.com/dragonwar101",
  },
  ogImage: "https://nbarkiya.xyz/profile-img.jpg",
  iconIco:
    "https://res.cloudinary.com/dbfvcn3f6/image/upload/v1692357384/assets/naman-favicon.ico",
  logoIcon:
    "https://res.cloudinary.com/dbfvcn3f6/image/upload/v1692357294/assets/naman-logo.png",
  keywords: [
    "Mohamed Tarek",
    "Full Stack Developer",
    "Web Developer Portfolio",
    "Next.js developer portfolio",
    "React developer portfolio",
    "Developer portfolio",
    "Portfolio website",
    "Next.js",
    "Modern portfolio website",
    "Frontend developer portfolio",
    "Full stack developer portfolio",
    "Open source portfolio",
    "Web developer portfolio",
    "Responsive portfolio",
    "React.js portfolio",
    "Tailwind CSS portfolio",
    "Developer showcase",
    "Free portfolio",
    "Next.js 14",
    "Career timeline",
    "Portfolio with dark mode",
    "GitHub portfolio",
  ],
};
